{
  "hash": "3c606b17567eaa7dd92908686e006b7d",
  "result": {
    "markdown": "---\ntitle: \"Introduction to Hypothesis Testing \"\nsubtitle: \"\"\nauthor: \"Esteban Montenegro-Montenegro, PhD\"\ninstitute: \"Psychology and Child Development\"\ntitle-slide-attributes:\n    data-background-image: \"background1.png\"\n    data-background-opacity: \"0.5\"\nformat: \n revealjs:\n   theme: [default, custom.scss]\n   slide-number: true\n   self-contained: false\n   chalkboard: \n    theme: whiteboard\neditor: visual\nbibliography: references.bib\n#nocite: | \n#  @apa7\ncsl: apa.csl\n---\n\n\n## Today's aims {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We will study the concept of p-value a.k.a significance test.\n\n-   I will introduce the concept of hypothesis testing.\n\n-   I will also introduce the mean comparison for independent groups.\n\n\n::: {.cell}\n\n:::\n\n\n## What is a p-value? {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   ***p-value*** stands for *probability value*.\n\n-   It was born as a measure to reject a hypothesis.\n\n-   In statistics and science, we always have hypothesis in mind. Statistics translates our hypothesis into evaluations of our hypothesis.\n\n-   For example, we often ask questions to our selves such as: why my boyfriend won't express her feelings? and then we ask, is this related to gender? Is it true that women share easily their emotions compare to men? If so, does it happen only to me? Is this a coincidence?\n\n-   We can create a hypothesis with these questions, let's try to write one:\n\n$H_{1}$ = There is a difference in emotional expression between cisgender women and cisgender men.\n\n-   This is our *alternaive hypothesis* but we need a *null hypothesis*:\n\n$H_{0}$ = There is *no* difference in emotional expression between cisgender women and cisgender men.\n\n-   That was easy you might think, but why do we need a null statement?\n\n    -   Science always starts with a *null* believe, and what we do as scientist is to collect evidence that might help to reject the null hypothesis. If you collect data to support your alternative hypothesis you would be doing something called \"confirmation bias\".\n    -   Confirmation bias consist of collecting information that only supports your alternative hypothesis.\n    -   For example, you start collecting data that only proofs that all swans are white, instead of looking at information that helps to reject the null: not all swans are white.\n\n## What is a p-value? II {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We can write out *null* hypothesis in a statistical statement:\n\n$H_{0}$ = The mean difference in emotional expression between cisgender women and cisgender men is equal to zero.\n\n-   In the previous hypothesis we know that we are focusing in the mean difference, it is more specific.\n\n-   The very first step to test our null hypothesis is to create a ***null model***.\n\n-   A ***null model*** is a model where there is not any difference between groups, or there is not relationship between variables.\n\n## What is a p-value? III {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   In my new model I will find a null model for the correlation between rumination and depression.\n\n-   To create our new model we will re sample and shuffle our observed data. This is similar to have two decks of cards and you shuffle your cards multiple times until it is hard to guess which card will come next, and imagine cards have equal probability to be selected.\n\n-   This procedure is called *permutations*, this will help us to create a distribution of *null correlations*. This means, all the correlations produced by my null model are produced by *chance*.\n\n## What is a p-value? IV {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   Let's see the following example, remember the estimated correlation between rumination and depression is $r= 0.58$. This null model will help us to know if the correlation is explained by chance.\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrum <- read.csv(\"ruminationComplete.csv\", na.string = \"99\") ## Imports the data into R\n\nrum_scores <- rum %>% mutate(rumination = rowSums(across(CRQS1:CRSQ13)),\n                             depression =  rowSums(across(CDI1:CDI26))) ### I'm calculating\n                                                                       ## total scores\n\n\ncorr <- cor(rum_scores$rumination, rum_scores$depression,\n            use =  \"pairwise.complete.obs\") ## Correlation between rumination and depression\n\n### Let's create a distribution of null correlations\n\nnsim <- 100000\n\ncor.c <- vector(mode = \"numeric\", length = nsim)\n\nfor(i in 1:nsim){\ndepre <- sample(rum_scores$depression, \n                212, \n                replace = TRUE)\n\nrumia <- sample(rum_scores$rumination, \n                212, \n                replace = TRUE)\n\ncor.c[i] <- cor(depre, rumia, use =  \"pairwise.complete.obs\")\n}\n\n\nhist(cor.c, breaks = 120, \n     xlim= c(min(cor.c), 0.70),\n     main = \"Histograma of null correlations\")\nabline(v = corr, col = \"darkblue\", lwd = 2, lty = 1)\nabline(v = c(quantile(cor.c, .025),quantile(cor.c, .975) ),\n col= \"red\",\n lty = 2,\n lwd = 2)\n```\n:::\n\n\n## Figure\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n:::\n\n## What is a p-value? V {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\nLet's estimate the probability of seeing $r = 0.58$ according to our null model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npVal <- 2*mean(cor.c >= corr)\npVal\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\n-   The probability is a number close to $0.00$.\n\n-   We now conclude that a correlation as extreme as $r = 0.58$ is not explained by chance alone.\n\n::: callout-note\n### Note:\n\nThe ugly rule of thumb is to consider a p-value \\<= .05 as evidence of small probability.\n:::\n\n## Mean difference {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We can also do the same for the difference between means.\n\n-   In this example, my null model is a model with null differences.\n\n-   I also conducted permutations on this example.\n\n-   We will estimate if the difference by sex in rumination is explained by chance.\n\n-   In this sample the mean difference in rumination between males and females is $\\Delta M$ = 2.74.\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1236)\n\nob.diff <- mean(rum_scores$rumination[rum_scores$sex==0], na.rm = TRUE )- mean(rum_scores$rumination[rum_scores$sex==1], na.rm = TRUE)\n\n### let's create a distribution of null differences\n\nnsim <- 100000\n\ndiff.c <- vector(mode = \"numeric\", length = nsim)\n\n### This is something called \"loop\", you don't have to pay attention to this.\n\nfor(i in 1:nsim){\nwomen <- sample(rum_scores$rumination[rum_scores$sex==0], \n                length(rum_scores$rumination[rum_scores$sex==0]), \n                replace = TRUE)\n\nmen <- sample(rum_scores$rumination[rum_scores$sex==1], \n                length(rum_scores$rumination[rum_scores$sex == 1]), \n                replace = TRUE)\n\ndiff.c[i] <- mean(women,  na.rm = TRUE)-mean(men,  na.rm = TRUE)\n} \n\n\nhist(diff.c, breaks = 120, \n     #xlim= c(min(diff.c), 0.70),\n     main = \"Histogram of Null Differences\")\nabline(v = ob.diff, col = \"darkblue\", lwd = 2, lty = 1)\nabline(v = c(quantile(diff.c, .025), quantile(diff.c, .975) ),\n col= \"red\",\n lty = 2,\n lwd = 2)\n```\n:::\n\n\n## Figure\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n:::\n\n-   We can see the probability of seeing a value as large as 2.74\n\n\n::: {.cell}\n\n```{.r .cell-code}\npVal <- 2*mean(diff.c >= ob.diff)\npVal\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.99652\n```\n:::\n:::\n\n\n## Mean difference II {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   In real life, we don't have to estimate a null model \"by hand\" as I did before.\n\n-   `R` and JAMOVI will help us on that because the null model is already programmed.\n\n-   In addition, when we compare independent means, we don't usually do permutations. We follow something called the $t$ - distribution , let's study more about this distribution: [t-distribution](https://en.wikipedia.org/wiki/Student%27s_t-distribution).\n\n## Mean difference III {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   The $t$-distribution helped to develop the test named `t`-Student Test.\n\n-   In this test we use the $t$-distribution as our model to calculate the probability to observe a value as extreme as 2.74.\n\n-   But this probbaility will be estimated following the Cumulative Density Function (CDF) of the $t$-distribution.\n\n## $t$-Test {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   The Student's test is also known as a the \"t-test\".\n\n-   In this test, we will transform the mean difference of both groups into a $t$ value.\n\n\n```{=tex}\n\\begin{equation}\nt= \\frac{\\bar{X}_{1} - \\bar{X}_{2}}{\\sqrt{\\Big [\\frac{(n_{1}-1)s^{2}_{1}+(n_{2}-1)s^{2}_{2}}{n_{1} + n_{2}-2}\\Big ]\\Big [\\frac{n_{1}+n_{2}}{n_{1}n_{2}} \\Big ]}}\n\\end{equation}\n```\n\n-   In this transformation $n_{1}$ is the sample size for group 1, $n_{2}$ is the sample size for group 2, $s^2$ means variance. The $\\bar{X}$ represents the mean.\n\n-   This formula will help us to tranform the oberved difference in means to a value that comes from the $t$-distribution.\n\n## $t$-Test III {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   Remember we talked about the $t$-distribution's CDF. This CDF will help us to estimate the probability of seeing a value. the *y-axis* represents probability values.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-8-1.png){width=864}\n:::\n:::\n\n\n## $t$-Test IV {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We can see how useful is a $t$-test by presenting a applied example.\n\n-   In this example we will try to reject the null hypothesis that says:\n\n***\"The rumination score in males is equal to the rumination score in females\"***\n\n-   We represent this hypothesis in statitistic like this:\n\n\n```{=tex}\n\\begin{equation}\nH_{0}: \\mu_{1} = \\mu_{0}\n\\end{equation}\n```\n\n-   Also in this example I'm introducing a new function in `R` named `t.test()`. This is the function that will helps to know if we can reject the null hypothesis.\n\n-   The function `t.test()` requires a formula created by using tilde `~`.\n\n-   In `R` the the variable on the right side of `~` is the *independent variable*, the variable on the left side of `~` is the *dependent variable*.\n\n-   In a independent samples $t$-test the independent variable is always the group, and the dependent variable is always any continuous variable.\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rumination ~ sex, data = rum_scores, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  rumination by sex\nt = 2.2457, df = 203, p-value = 0.0258\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n 0.3347849 5.1535481\nsample estimates:\nmean in group 0 mean in group 1 \n       31.20896        28.46479 \n```\n:::\n:::\n\n\n-   In this example, we found that the $p$-value is 0.03 and the $t$-value is 2.25. This means:\n\n\\*\\*\\*\"IF we repeat the same analysis with multiple samples the probability of finding a\\*\\*\\* $t$-value = 2.25 is p = 0.03, under the assumptions of the null model\".\n\n-   This is a very small probability, what do you think? Is 2.25 a value explainable by chance alone?\n\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n:::\n\n## $t$-test Assumptions {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We haven't talked about the assumptions of the t-test model.\n\n-   Remember that all models have assumptions, we have to assume something to study Nature.\n\n-   The $t$-test model assumes that the difference in means is generated by a normally distributed process.\n\n-   It also assumes that variances are equal on both groups.\n\n-   Let's see what happens when we assume equal variances but the data does not come from a process with equal variances:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nset.seed(1234)\n\nN1 <- 50 ## Sample size group 1\n\nN2 <- 50 ### sample size group 2\n\nMean1 <- 100 ## Mean group 1\n\nMean2 <- 20 ### Mean group 2\n\nresults <- list()\n\n\nfor(i in 1:10000){\ngroup1 <- rnorm(N1, mean = Mean1, sd = 100) ### variances or standard deviation are not equal\n\ngroup2 <-  rnorm(N2, mean = Mean2, sd = 200) ### variances or standard deviation are not equal\n\ndataSim <- data.frame(genValues = c(group1,group2), \n                      groupVar = c(rep(1,N1),rep(0,N2)))\n\nresults[[i]] <- t.test(genValues ~ groupVar, data = dataSim, var.equal = TRUE)$p.value\n}\n\n### Proportion of times we rejected the null hypothesis\n\ncat(\"Proportion of times we rejected the null hypothesis\",sum(unlist(results) <= .05)/length(results)*100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nProportion of times we rejected the null hypothesis 70.5\n```\n:::\n:::\n\n\n-   We successfully rejected the null hypothesis in only 70.5% of the data sets generated. But in reality the $t$-test should reject the null hypothesis 100% of the times.\n\n-   Let's check when we assume equal variances in our $t$ - test and the model that generates is actually a process with equal variances:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nset.seed(1234)\n\nN1 <- 50\n\nN2 <- 50\n\nMean1 <- 100\n\nMean2 <- 20\n\nresults_2 <- list()\n\nfor(i in 1:10000){\n  \ngroup1 <- rnorm(N1, mean = Mean1, sd = 5) ## equal variances or standard deviation\n\ngroup2 <-  rnorm(N2, mean = Mean2, sd = 5) ## equal variances or standard deviation\n\ndataSim <- data.frame(genValues = c(group1,group2), \n                      groupVar = c(rep(1,N1),rep(0,N2)))\n\nresults_2[[i]] <- t.test(genValues ~ groupVar, data = dataSim, var.equal = TRUE)$p.value\n}\n\n### Probability of rejecting the null hypothesis\n\ncat(\"Proportion of times we rejected the null hypothesis\", sum(unlist(results_2) <= .05)/length(results_2)*100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nProportion of times we rejected the null hypothesis 100\n```\n:::\n:::\n\n\n-   This time we are rejecting the null hypothesis 100% of the times. This is what we were looking for! Remember that we generated data from a process where group 1 had a mean of 100, and the group 2 had a mean of 20. The t-test should reject the null hypothesis every time I generate new data sets, but this doesn't happen when I made the wrong assumption: *I assumed equal variances when I should not do it*.\n\n-   Summary: when we wrongly assume that the variances are equal between groups, we decrease the probability to reject the null hypothesis when the null should be rejected. This is bad!\n\n-   These simulations showed the relevance of respecting the assumptions of the $t$-test.\n\n## How do we know if my observed data holds the assumption ? {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   There are tests to evaluate the assumption of equivalence of variance between groups.\n\n-   The most used test to evaluate the homogeneity of variance is the Levene's Test for Homogeneity of Variance.\n\n-   We can implement this test in `R` using the function `leveneTest()` , this function comes with the `R` package `car`. You might need to install this package in case you don't have it installed in your computer, you can run the this line of code to install it: `install.packages(\"car\")`\n\n-   I'm going to test if the variance of rumination holds the assumption of equality of variance by sex:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n\nleveneTest(rumination ~ as.factor(sex), \n           data = rum_scores) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   1  0.2541 0.6148\n      203               \n```\n:::\n:::\n\n\n-   In this test the null hypothesis is \"The variances of group 1 and group 2 are equal\", if the $p$-value is less or equal to 0.05 we reject the null hypothesis. In the output above you can see the p-value under the column `Pr(>F)`.\n\n-   In the case of rumination, the $p$-value = 0.61, given that the $p$-value is higher than 0.05, we don't reject the null hypothesis. We can assume the variances of rumination by sex are equal.\n\n## How do we know if my observed data holds the assumption ? II {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   What happens if the Levene's Test rejects the null hypothesis of homogeneity of variance?\n\n-   Can we continue using the $t$ - test to evaluate my hypothesis?\n\n-   The answer is: Yes you can do a $t$-test but there is a correction on the degrees of freedom. We will talk more about degrees of freedom in the next sessions.\n\n-   If you cannot assume equality of variances, all you have to do in `R` is to switch the argument `var.equal = TRUE` to `var.equal = FALSE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rumination ~ sex, data = rum_scores, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  rumination by sex\nt = 2.2841, df = 149.72, p-value = 0.02377\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n 0.3702483 5.1180847\nsample estimates:\nmean in group 0 mean in group 1 \n       31.20896        28.46479 \n```\n:::\n:::\n\n\n-   Now , the output says we are performing a Welch Two Sample t-test, Welch was tha mathematician who found the correction.\n\n## Effect size {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   Up to this point we have studied how we test our hypothesis when we compare independent means, but we still have to answer the question, how large is a large difference between means? Or, how small is a small difference? In fact, what is considered a small difference?\n\n-   These questions were answered by Jacob Cohen (1923-1998).\n\n-   Cohen created a standardized measure to quantify the magnitude of the difference between means.\n\n-   Let's see a pretty plot about it in this [link.](https://rpsychologist.com/cohend/)\n\n## Time to check more formulas {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n***Cohen's*** $d$ Effect Size:\n\n\n```{=tex}\n\\begin{equation}\nES = \\frac{\\bar{X}_{1}-\\bar{X}_{2}}{\\sqrt{\\Big[\\frac{s^2_{1}+s^2_{2}}{2} \\Big ]}}\n\\end{equation}\n```\n\nWhere:\n\n-   $ES$ = is effect size.\\\n-   $\\bar{X}$ = Mean.\\\n-   $s^2$ = variance.\\\n\n## Effect size example {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   Let's compute an effect size in `R`. In this example we will resume our $t$-test example of rumination by sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(rumination ~ sex, data = rum_scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  rumination by sex\nt = 2.2841, df = 149.72, p-value = 0.02377\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n 0.3702483 5.1180847\nsample estimates:\nmean in group 0 mean in group 1 \n       31.20896        28.46479 \n```\n:::\n:::\n\n\n-   In the $t$- test output we have information we can use to compute the effect size. We have the mean for each group $M_{(female)} = 31.21$, $M_{(male)}= 28.46$. We already know that the difference between groups is not explained by chance alone ($p$= 0.02) because the p-value is smaller than 0.05.\n\n-   Now let's compute the effect size,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n### This will create tidy table by group (sex)\nInfoByBroup <- rum_scores %>% group_by(sex) %>%\n    summarize(Mean = mean(rumination, na.rm = TRUE),  \n          Var = var(rumination, na.rm = TRUE))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table>\n<caption>Rumination mean and variance by sex</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> sex </th>\n   <th style=\"text-align:right;\"> Mean </th>\n   <th style=\"text-align:right;\"> Var </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 31.21 </td>\n   <td style=\"text-align:right;\"> 71.88 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28.46 </td>\n   <td style=\"text-align:right;\"> 64.40 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Effect size computation**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nmeanFemales <- InfoByBroup$Mean[1]\n\nmeanMales <- InfoByBroup$Mean[2]\n\nvarianceFemales <- InfoByBroup$Var[1]\n\nvarianceMales <- InfoByBroup$Var[2]\n\neffectSize <- (meanFemales-meanMales)/sqrt((varianceFemales+varianceMales)/2)\n\ncat(\"The effect size of sex on rumination is\", \"d =\", round(effectSize,2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe effect size of sex on rumination is d = 0.33\n```\n:::\n:::\n\n\n-   According to @cohen_statistical_2013 a small effect size is $d = 0.20$, a medium effect size is $d = 0.50$, a large effect size is $d= .80$\n\n## Effect size example II {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We can make this calculation more fun. Let's imagine you are a clinician, and you need a way to understand how large is the difference in rumination and depression. You need to find a way to quantify which variable you should pay more attention, which variable has larger differences between cisgender males and cisgender females.\n\n-   Why would you care about differences between cisgender males and cisgender females? Why would you care to compare the differences between rumination and depression?\n\n-   Firstly, we need to compute the depression score. In the `rumination` data set you'll find columns named `CDI` these are the items that correspond to the *Children's Depression Inventory*. We will use this items to compute a total score.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrum_scores <- rum_scores %>% \n  mutate(depression = rowSums(across(CDI1:CDI26))) ## Computes total score\n```\n:::\n\n\n***We need to check if the variances our depression score are equal between groups before running a*** $t$-test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n\nleveneTest(depression ~ as.factor(sex), \n           data = rum_scores) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   1  0.8682 0.3526\n      205               \n```\n:::\n:::\n\n\n-   The Leven's Test for Homogeneity of Variance did not reject the null hypothesis of equality of variances. Hence, we can hold the assumption of equality of variances. We don't need to perform a correction\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## This test assumes equality of variances after performing the Levene's Test.\nt.test(depression ~ sex, data = rum_scores, var.equal = TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  depression by sex\nt = 2.5468, df = 205, p-value = 0.01161\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n 0.5257305 4.1298205\nsample estimates:\nmean in group 0 mean in group 1 \n      11.257353        8.929577 \n```\n:::\n:::\n\n\n-   Nice! Look at the result, we found a difference in depression by cisgender (sex), and it is not explained by chance alone.\n\n::: {.callout-important collapse=\"true\"}\nHow do you know the difference is not explained by chance alone?\n:::\n\n## Effect size example III {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   After estimating the $t-test$ of depression by sex, we can now quantify the effect's magnitude:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nInfoByBroupDepression <- rum_scores %>% group_by(sex) %>%\n    summarize(Mean = mean(depression, na.rm = TRUE),  \n          Var = var(depression, na.rm = TRUE))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table>\n<caption>Depression mean and variance by sex</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> sex </th>\n   <th style=\"text-align:right;\"> Mean </th>\n   <th style=\"text-align:right;\"> Var </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 11.26 </td>\n   <td style=\"text-align:right;\"> 36.86 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 8.93 </td>\n   <td style=\"text-align:right;\"> 43.04 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Effect size computation**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nmeanFemales <- InfoByBroupDepression$Mean[1]\n\nmeanMales <- InfoByBroupDepression $Mean[2]\n\nvarianceFemales <- InfoByBroupDepression$Var[1]\n\nvarianceMales <- InfoByBroupDepression$Var[2]\n\neffectSizeDepression <- (meanFemales-meanMales)/sqrt((varianceFemales+varianceMales)/2)\n\ncat(\"The effect size of sex on depression is\", \"d =\", round(effectSizeDepression,2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe effect size of sex on depression is d = 0.37\n```\n:::\n:::\n\n\n-   As you can see the effect size of sex on depression is $d=$ 0.37 whereas in rumination the effect size of sex is $d=$ 0.33\n\n## Effect size example (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   What is your conclusion as a clinician? Is rumination too much different from depression?\n\n-   Should we focus on an intervention that addresses depression or/and rumination differently according to sex?\n\n-   Should you create a depression intervention accounting for the effect of sex ? Can you ignore rumination for your intervention?\n\n-   Should we focus mainly on women because the difference is large between groups?\n\n## Effect size example (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   As always there are other ways to compute the effect size.\n-   The next formula takes into account occasions when the sample size is not the same between groups.\n\n\n```{=tex}\n\\begin{equation}\nES = \\frac{\\bar{X}_{1} - \\bar{X}_{2}}{\\sqrt{\\Big [\\frac{(n_{1}-1)s^{2}_{1}+(n_{2}-1)s^{2}_{2}}{n_{1} + n_{2}-2}\\Big ]}}\n\\end{equation}\n```\n\nWhere:\n\n$\\bar{X}$ = Mean\\\n\n$s^2$ = variance\\\n\n$n$ = sample size\\\n\n-   You can study more about effect sizes by clicking this [link](https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863/full). It is an article with a good explanation and summary. We will talk about effect sizes again when we study Analysis of Variance (ANOVA).\n\n## Effect size example (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We can also estimate the effect sizes with pacakages already programmed to be used in `R`. In this case we can use the package `effectsize`.\n\n-   You don't have this package installed in your `R` installation. You will have to install the package by running `install.packages(\"effectsize\", dependencies = TRUE)`.\n\n-   You only need to install a package one time. You don't have to install packages everytime you open RStudio.\n\n::: panel-tabset\n## Rumination\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effectsize)\n\ncohens_d(rumination ~ sex,\n         data = rum_scores) ### Equal variances assumed\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCohen's d |       95% CI\n------------------------\n0.33      | [0.04, 0.62]\n\n- Estimated using pooled SD.\n```\n:::\n\n```{.r .cell-code}\ncohens_d(rumination ~ sex,\n         data = rum_scores, \n         pooled_sd = FALSE) ### does not assume equal variances\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCohen's d |       95% CI\n------------------------\n0.33      | [0.04, 0.62]\n\n- Estimated using un-pooled SD.\n```\n:::\n:::\n\n\n## Depression\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d(depression ~ sex,\n         data = rum_scores) ### Equal variances assumed\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCohen's d |       95% CI\n------------------------\n0.37      | [0.08, 0.66]\n\n- Estimated using pooled SD.\n```\n:::\n\n```{.r .cell-code}\ncohens_d(depression ~ sex,\n         data = rum_scores, \n         pooled_sd = FALSE) ### does not assume equal variances\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCohen's d |       95% CI\n------------------------\n0.37      | [0.07, 0.66]\n\n- Estimated using un-pooled SD.\n```\n:::\n:::\n\n:::\n\n# Let's jump into JAMOVI software {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n## JAMOVI {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   I hope you remember JAMOVI. I mentioned this software in the first class.\n\n-   It is also listed in the syllabus.\n\n-   This is a software that runs `R` using a interface that does not require to write the `R` code. JAMOVI will write the `R` code for you behind scenes, it also runs the code for you. Pretty awesome isn't it?\n\n![](face.jpg){.absolute bottom=\"0\" right=\"50\" width=\"300\" height=\"360\"}\n\n# Central Limit Theory (CLT) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n## Central Limit Theory (CLT) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   The Central Limit Theory (CLT) is a fact, it describes a rule that happens everywhere in Nature.\n\nThe CLT states: ***For any population with mean*** $\\mu$ and standard deviation $\\sigma$, the distribution of sample means for sample size $n$ will have a mean of $\\mu$ and a standard deviation of $\\frac{\\sigma}{\\sqrt{n}}$ and will approach a normal distribution as $n$ approaches infinity.\n\n-   The beauty of this theorem is due to:\n\n-   it describes the distribution of sample means for any population, no matter what shape, mean, or standard deviation.\n\n-   The distribution of sample means \"approaches\" a normal distribution very rapidly.\n\n-   It is better to explain this theorem with a simulation, as always we do in this class.\n\n## Central Limit Theorem (CLT) (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   In this example I'll generate 1000 \"datasets\" from a Gaussian process (normal distribution) with M = 60, sd = 100. Each data set will contain 10 observations.\n\n-   After generating 1000 data sets, I'm estimating the mean of those simulated values.\n\n-   Imagine you are asking the question how many minutes do you need to take a shower? to 10 participants, you then conduct the same study the next day with a different set of 10 participants every day until you get 1000 sets of 10 participants.\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(563)\nN <- 10\n\nM <- 60\n\nSD <- 100\n\n## Number of data sets or replications\nrep <- 1000\n\nresults <- list()\n\nfor(i in 1:rep){\n\nresults[[i]] <- mean(rnorm(n = N, mean = M, sd = SD))\n}\n```\n:::\n\n\n## Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(density(unlist(results)),\n     xlab = \"Sample means\",\n     ylab = \"p(y) or likelikood\",\n     main = \"Density plot of Sample means\")\n```\n\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n:::\n\n## Central Limit Theorem (CLT) (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   There is more beautiful qualities about the CLT. This rule applies to all distributions. When you increase the number of observations per sample, and the number of sample approach infinity. The sample of means will look Gaussian distributed (normally distributed).\n\n-   Remember the Poisson distribution I mentioned some lectures behind?\n\n-   As you can see the Poisson distribution after generating 1 data set of 10 observations doesn't look like a Gaussian process at all!\n\n-   Can the sample of means from a Poisson process generate a pretty bell shape?\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(563)\nplot(density(rpois(n = 5,lambda = 8)),\n     xlab = \"Number of times people take a shower in a week\",\n     ylab = \"p(y) or likelihood\",\n     main = \"Density plot of a Poisson distributed variable\")\n```\n:::\n\n\n## Figure or plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-31-1.png){width=1440}\n:::\n:::\n\n:::\n\n## Central Limit Theorem (CLT) (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   Let's find out the answer by simulating 1000 data sets:\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(563)\nN <- 10\n\nM <- 10\n\n## Number of data sets or replications\nrep <- 1000\n\nresults <- list()\n\nfor(i in 1:rep){\n\nresults[[i]] <- mean(rpois(n = N, lambda = M))\n}\n```\n:::\n\n\n## Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(density(unlist(results)),\n     xlab = \"Sample of means (Number of times people take a shower in a week)\",\n     ylab = \"p(y) or likelihood\",\n     main = \"Density plot of sample of means from a Poisson data process\")\n```\n\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-33-1.png){width=960}\n:::\n:::\n\n:::\n\n-   There is also something even prettier, the mean estimated with all the means, is actually close to the data generating process. It is lovely! This is a natural rule!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(unlist(results))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.0076\n```\n:::\n:::\n\n\n## Central Limit Theorem (CLT) (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We saw that the mean of sample means is close to the data generating process mean , and it doesn't matter the type of distribution. However, take into account that there are probability distribution models that will require more than 800000000000 sampled means to approach the Gaussian shape. But eventually the distribution of all the means will look like a Gaussian distribution.\n\n-   In simple terms, what does it mean? It means that the ***mean*** is an unbiased ***estimate*** on average it tends to be close to the \"population\" mean. This is why we like the mean as an estimate , and we use it to test hypothesis.\n\n## Standard Error {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   The CLT will be helpful to introduce the concept of standard error.\n\n-   The Standard Error is a measure of how far is the mean of my sample from the true value in the data generating process.\n\n-   The Standard Error in the context of multiple samples is the standard deviation of all sampled means.\n\n-   We should go to another example:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nset.seed(563)\nN <- 10\n\nM <- 60\n\nSD <- 100\n\n## Number of data sets or replications\nrep <- 1000\n\nresults <- list()\n\nfor(i in 1:rep){\n\nresults[[i]] <- mean(rnorm(n = N, mean = M, sd = SD))\n}\n\ncat(\"The Standard Deviation of 1000 sampled means is\", sd(unlist(results)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe Standard Deviation of 1000 sampled means is 33.25718\n```\n:::\n:::\n\n\n-   in this example if we estimate the standard deviation of our sample means we get sd = 33.2571782.\n\n## Standard Error (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   In real life, you'll never know the standard deviation of sample means, because this is a simulated example.\n\n-   In real application you need to estimate how far your observed mean is from the true mean.\n\n-   We can use this estimation $\\frac{\\sigma}{\\sqrt(n)}$ to approximate how far we are from the mean. In this formula $\\sigma$ is the standard deviation and $n$ is the sample size.\n\n-   The standard error decreases when we increase the sample size, let's see another example:\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nset.seed(563)\n\nN <- seq(10, 10000, by = 10)\n\nM <- 60\n\nSD <- 100\n\nresults <- list()\n\nfor(i in 1:length(N)){\n\nresults[[i]] <- sd(rnorm(n = N[i], mean = M, sd = SD))/sqrt(N[i])\n}\n```\n:::\n\n\n## Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(x = N,\n     y = results,\n     type = \"l\",\n     xlab = \"Number of observations in each sample\",\n     ylab = \"Standard error\",\n     main = \"Line plot of Standard Error by sample size\")\n```\n\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-37-1.png){width=960}\n:::\n:::\n\n:::\n\n::: callout-important\nIn simple words: The standard error (SE) measures the distance from the true value in the data generating process.\n:::\n\n# More details about the Gaussian distribution {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n## The 68--95--99.7 Rule for a Normal Distribution {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   There is an important concept in frequentist statistics called \"confidence interval\"\n\n-   But before getting into details I need to explain a important property of the normal distribution.\n\n-   The following rule applies for the normal distribution:\n\n    -   68 $\\%$ of values will be between $\\mu$ - $\\sigma$ and $\\mu$ + $\\sigma$ .\n    -   95 $\\%$ of values will be between $\\mu$ - $2 \\sigma$ and $\\mu$ + $2 \\sigma$.\n    -   99.7 $\\%$ of values will be between $\\mu$ - $3 \\sigma$ and $\\mu$ + $3 \\sigma$\n\n-   We can see it by generating values from a Gaussian process:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nset.seed(3632)\n\ngeneratedValues <- rnorm(200000, mean = 50, sd = 2)\n\n### +-1 standard deviation form the mean\n\nupper <- 50 + 2\n\nlower <- 50 - 2\n\npercent1sigma <- (sum(generatedValues <= upper & generatedValues >= lower)\n/length(generatedValues))*100\n\n### +-2 standard deviation form the mean\n\nupper <- 50 + 2*2\n\nlower <- 50 - 2*2\n\npercent2sigma <- (sum(generatedValues <= upper & generatedValues >= lower)/length(generatedValues))*100\n\n### +-3 standard deviation form the mean\n\nupper <- 50 + 3*2\n\nlower <- 50 - 3*2\n\npercent3sigma <- (sum(generatedValues <= upper & generatedValues >= lower)/length(generatedValues))*100\n```\n:::\n\n\n-   68.35 $\\%$ of observations are located at $\\pm 1 \\sigma$ from the data generating process mean. That is true!\n\n-   95.45 $\\%$ of observations are located at $\\pm 2 \\sigma$ from the data generating process mean. That is true!\n\n-   99.74 $\\%$ of observations are located at $\\pm 3 \\sigma$ from the data generating process mean. That is true!\n\n## Allow me to use a metaphor {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n@westfall2013understanding:\n\n-   Imagine there is a lion or perhaps a coyote around your town. Every day the coyote moves around 20 km from the town, forming a circular perimeter. The town is right in the middle of the circle:\n\n![](lion.png)\n\n## Allow me to use a metaphor (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   As you can imagine the lion or coyote could move further from the town but it is always wondering around town chasing chickens or killing cows.\n\n-   We could collect data, for instance, the distance every day from town, and see on average how far it is from town. We could also estimate the standard deviation (\\sigma). This could be a good measure to see patterns, and be *confident* about the interval (circle) where the lion or coyote walks.\n\n## Allow me to use a metaphor (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   Let's imagine that the town is our data generating process mean value (\\mu). Also imagine that each time the lion or coyote walks around the town is an independent observed sample from the data generating process.\n\n-   We need to find a way to be confident that our observed data is closed to $\\mu$ (\"population mean\").\n\n-   A few minutes ago we saw that according to the a Gaussian distribution, you'll find 95 $\\%$ of the values around $\\pm 2 \\sigma$ from the mean. However, in our simulated data we found out that in reality you'll find more than 95 $\\%$. It was actually 95.45 $\\%$.\n\n-   We'll use this great property of the Gaussian distribution, but we will use $\\pm 1.96 \\sigma$ instead of $\\pm 2 \\sigma$. Why? because we want to be closer to exactly find 95$%$ of the observations. This means, we want to be 95$\\%$ confident that we are close to $\\mu$, or the town following our example.\n\n-   We will estimate the confidence interval by computing:\n\n\n```{=tex}\n\\begin{equation}\n\\bar{x} \\pm 1.96 \\frac{\\hat{\\sigma}}{ \\sqrt{n}}\n\\end{equation}\n```\n\nWhere,\n\n$\\bar{x}$ is the estimated mean.\\\n$\\hat{\\sigma}$ is the estimated standard deviation.\\\n$1.96$ is the 97.5 percentile in the standard normal distribution (Gaussian).\\\n\n## Confidence Interval {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\nLet's compute the confidence interval by hand, we can use again the mean of the rumination score:\n\n\n```{=tex}\n\\begin{equation}\n30.25 \\pm 1.96  \\Big (\\frac{8.41}{\\sqrt{205}} \\Big )\n\\end{equation}\n```\n\n**We need to estimate the mean first:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRumMean <- mean(na.omit(rum_scores$rumination))\nRumMean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30.25854\n```\n:::\n:::\n\n\n**Second, we need to estimate the standard deviation:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(na.omit(rum_scores$rumination))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.406725\n```\n:::\n:::\n\n\n**Now we can estimate the 95**$\\%$ confidence interval:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nupperCI <- 30.26+1.96*(8.41/sqrt(205))\n\nlowerCI <- 30.26-1.96*(8.41/sqrt(205))\n\ncat(\"The 95% confidence interval for the mean is:\", \n        \"upper-bound=\",\n        round(upperCI,2), \n        \"lower-bound=\",\n          round(lowerCI,2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe 95% confidence interval for the mean is: upper-bound= 31.41 lower-bound= 29.11\n```\n:::\n:::\n\n\n**We can also estimate the confidence interval using the package `rcompanion`**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rcompanion)\ngroupwiseMean(rumination ~ 1,\n              data   = rum_scores,\n              conf   = 0.95,\n              digits = 3,\n              na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   .id   n Mean Conf.level Trad.lower Trad.upper\n1 <NA> 205 30.3       0.95       29.1       31.4\n```\n:::\n:::\n\n\n-   There is something to note here. What you are doing is just multipliying the standard error of the mean by 1.96. This value = 1.96 is called ***critical value***.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##Standard error multiplied by 1.96\n1.96*(8.41/sqrt(205))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.151265\n```\n:::\n:::\n\n\n-   With the information above we could interpret our result as follows:\n\n***I am approximately 95***$\\%$ confident that $\\mu$ is within 1.15 score points of the sample average 30.26.\n\n## Confidence Interval Intepretation {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   Many of the concepts studied up to this point come from a theory called \"frequentist\".\n\n-   The frequentist theory studies the probability in terms of long run events. In this approach we have to imagine that we repeat the same experiment or study several times. Only if we repeat the same study several times we'll be able to create a confidence interval.\n\n-   This is, of course theoretical. We are able to calculate confidence intervals with one sample. But, this interval is only an approximation.\n\n-   The interpretation of the confidence interval demands to imagine that you repeat the same study $n$ number of times. Hence the interpretation would be:\n\n*Since* $\\mu$ will lie within the upper and lower limits of similarly constructed intervals for 95% of the repeated samples,my sample is likely to be one of those samples where $\\mu$ is within the upper and lower limits, and I am therefore 95% confident that $\\mu$ is between 29.1 and 31.4.\n\n\n```{=tex}\n\\begin{equation}\n29.1 \\le \\mu \\le 31.4\n\\end{equation}\n```\n\n## Confidence Interval: multiple means {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hypothesisTesting_files/figure-revealjs/unnamed-chunk-44-1.png){width=960}\n:::\n:::\n\n\n-   Let's imagine a ask the same question: how many minutes do you need to take a shower?\n-   We could ask the same question to 50 different people 100 000 times, and then estimate the mean. The frequentist theory says that the true value will be among the 95$\\%$ of the sampled means.\n\n# The final part ... I promise {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n## Repeated measures: compare two dependent means {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We have only studied how to test the difference between independet groups.\n\n-   However, many times we have research designs where we do a pre-test and a post-test.\n\n-   For example, I could create an intervantion to treat depression. If I want to evaluate if there is an effect of the intervention I could measure the depression levels before the intervention, after that my participants will receive my new depression treatment. After they finish the intervention I measure again thei levels of depression.\n\n-   In this example, we would like to see a lower score in depression after the intervention. We would also like to test if the mean difference between time 1 and time 2 is explained by chance alone.\n\n***Null hypothesis:*** \\begin{equation}\nH_{0} = \\mu_{posttest} = \\mu_{pretest}\n\\end{equation}\n\n## Repeated measures: compare two dependent means (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n\n```{=tex}\n\\begin{equation}\nt = \\frac{\\sum D}{\\sqrt{\\frac{n \\sum D^2 - \\big (\\sum D \\big )^2}{n-1}}}\n\\end{equation}\n```\n\n$D$ is the difference between each individual's score from the first to the second time point.\n\n$\\sum D$ is the sum of all the differences between groups of scores.\n\n$\\sum D^2$ is the sum of the differences squared between groups of scores.\n\n$n$ is the number of pairs of observations.\n\n## Repeated measures: compare two dependent means (cont.) {.smaller .scrollable background-image=\"slide2.png\" background-opacity=\"0.5\"}\n\n-   We can test if the mean difference in life expectancy is explained by chance.\n\n-   Let's compare years 2019 and 2020:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlifeExpec <- read.csv(\"lifeExpect.csv\")\n\nt.test(lifeExpec$X2019, lifeExpec$X2020, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  lifeExpec$X2019 and lifeExpec$X2020\nt = -0.19141, df = 243, p-value = 0.8484\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -0.07583952  0.06240551\nsample estimates:\nmean difference \n   -0.006717005 \n```\n:::\n:::\n\n\nWe failed to reject the null hypothesis according to the $t$-test for dependent means. How did we arrived to this conclusion?\n\n::: callout-tip\nPay attention to the $p-value$. Do you remember the null hypothesis in this case?\n:::\n\n## References {background-image=\"slide2.png\" background-opacity=\"0.5\"}\n",
    "supporting": [
      "hypothesisTesting_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}